import 'dotenv/config'
import { nanoid } from 'nanoid'
import { type InferInsertModel } from 'drizzle-orm'
import { db } from './index'
import { assets } from './schema'

const seedAssets: InferInsertModel<typeof assets>[] = [
  // LAPTOPS
  {
    id: nanoid(),
    assetTag: 'ORO-LT-001',
    name: 'MacBook Air M2 13"',
    category: 'LAPTOP',
    status: 'ASSIGNED',
    assignedTo: 'Rahul Sharma',
    purchaseDate: '2025-01-15',
    purchaseCost: '95000.00',
    notes: 'Primary development laptop',
  },
  {
    id: nanoid(),
    assetTag: 'ORO-LT-002',
    name: 'Dell Latitude 5440',
    category: 'LAPTOP',
    status: 'IN_STOCK',
    assignedTo: null,
    purchaseDate: '2025-02-10',
    purchaseCost: '78000.00',
    notes: null,
  },
  {
    id: nanoid(),
    assetTag: 'ORO-LT-003',
    name: 'Lenovo ThinkPad E14',
    category: 'LAPTOP',
    status: 'ASSIGNED',
    assignedTo: 'Priya Reddy',
    purchaseDate: '2024-11-20',
    purchaseCost: '72000.00',
    notes: 'Office laptop',
  },
  {
    id: nanoid(),
    assetTag: 'ORO-LT-004',
    name: 'HP ProBook 450 G10',
    category: 'LAPTOP',
    status: 'IN_REPAIR',
    assignedTo: null,
    purchaseDate: '2024-08-05',
    purchaseCost: '68000.00',
    notes: 'Keyboard replacement required',
  },
  {
    id: nanoid(),
    assetTag: 'ORO-LT-005',
    name: 'MacBook Pro M3 14"',
    category: 'LAPTOP',
    status: 'RETIRED',
    assignedTo: null,
    purchaseDate: '2023-03-12',
    purchaseCost: '145000.00',
    notes: 'Replaced after hardware failure',
  },
  {
    id: nanoid(),
    assetTag: 'ORO-LT-006',
    name: 'Dell Inspiron 14',
    category: 'LAPTOP',
    status: 'IN_STOCK',
    assignedTo: null,
    purchaseDate: '2025-03-18',
    purchaseCost: '62000.00',
    notes: 'Ready for new employee',
  },

  // MONITORS
  {
    id: nanoid(),
    assetTag: 'ORO-MN-001',
    name: 'Dell UltraSharp U2723QE',
    category: 'MONITOR',
    status: 'ASSIGNED',
    assignedTo: 'Arjun Kumar',
    purchaseDate: '2024-06-14',
    purchaseCost: '52000.00',
    notes: '4K USB-C monitor',
  },
  {
    id: nanoid(),
    assetTag: 'ORO-MN-002',
    name: 'LG 27UP850',
    category: 'MONITOR',
    status: 'IN_STOCK',
    assignedTo: null,
    purchaseDate: '2025-01-25',
    purchaseCost: '42000.00',
    notes: null,
  },
  {
    id: nanoid(),
    assetTag: 'ORO-MN-003',
    name: 'Samsung ViewFinity S7',
    category: 'MONITOR',
    status: 'ASSIGNED',
    assignedTo: 'Sneha Rao',
    purchaseDate: '2024-09-08',
    purchaseCost: '39000.00',
    notes: 'Used for design work',
  },
  {
    id: nanoid(),
    assetTag: 'ORO-MN-004',
    name: 'BenQ PD2705U',
    category: 'MONITOR',
    status: 'IN_REPAIR',
    assignedTo: null,
    purchaseDate: '2023-12-10',
    purchaseCost: '48000.00',
    notes: 'Display flickering',
  },
  {
    id: nanoid(),
    assetTag: 'ORO-MN-005',
    name: 'Acer CB272',
    category: 'MONITOR',
    status: 'RETIRED',
    assignedTo: null,
    purchaseDate: '2022-05-16',
    purchaseCost: '21000.00',
    notes: 'End of useful life',
  },
  {
    id: nanoid(),
    assetTag: 'ORO-MN-006',
    name: 'HP E27 G5',
    category: 'MONITOR',
    status: 'IN_STOCK',
    assignedTo: null,
    purchaseDate: '2025-04-01',
    purchaseCost: '35000.00',
    notes: 'New office monitor',
  },

  // PHONES
  {
    id: nanoid(),
    assetTag: 'ORO-PH-001',
    name: 'iPhone 15 128GB',
    category: 'PHONE',
    status: 'ASSIGNED',
    assignedTo: 'Vikram Singh',
    purchaseDate: '2024-02-15',
    purchaseCost: '72000.00',
    notes: 'Company phone',
  },
  {
    id: nanoid(),
    assetTag: 'ORO-PH-002',
    name: 'Samsung Galaxy S24',
    category: 'PHONE',
    status: 'IN_STOCK',
    assignedTo: null,
    purchaseDate: '2024-04-20',
    purchaseCost: '68000.00',
    notes: 'Available for allocation',
  },
  {
    id: nanoid(),
    assetTag: 'ORO-PH-003',
    name: 'Google Pixel 8',
    category: 'PHONE',
    status: 'ASSIGNED',
    assignedTo: 'Meera Nair',
    purchaseDate: '2024-05-12',
    purchaseCost: '61000.00',
    notes: 'Android test device',
  },
  {
    id: nanoid(),
    assetTag: 'ORO-PH-004',
    name: 'iPhone 14',
    category: 'PHONE',
    status: 'IN_REPAIR',
    assignedTo: null,
    purchaseDate: '2023-09-10',
    purchaseCost: '62000.00',
    notes: 'Battery service required',
  },
  {
    id: nanoid(),
    assetTag: 'ORO-PH-005',
    name: 'OnePlus 12',
    category: 'PHONE',
    status: 'RETIRED',
    assignedTo: null,
    purchaseDate: '2022-07-25',
    purchaseCost: '55000.00',
    notes: 'Old test device',
  },
  {
    id: nanoid(),
    assetTag: 'ORO-PH-006',
    name: 'Samsung Galaxy A55',
    category: 'PHONE',
    status: 'IN_STOCK',
    assignedTo: null,
    purchaseDate: '2025-02-05',
    purchaseCost: '39000.00',
    notes: null,
  },

  // ACCESSORIES
  {
    id: nanoid(),
    assetTag: 'ORO-AC-001',
    name: 'Logitech MX Master 3S',
    category: 'ACCESSORY',
    status: 'ASSIGNED',
    assignedTo: 'Kiran Patel',
    purchaseDate: '2024-07-18',
    purchaseCost: '8500.00',
    notes: 'Wireless mouse',
  },
  {
    id: nanoid(),
    assetTag: 'ORO-AC-002',
    name: 'Logitech MX Keys Mini',
    category: 'ACCESSORY',
    status: 'IN_STOCK',
    assignedTo: null,
    purchaseDate: '2024-08-22',
    purchaseCost: '9200.00',
    notes: 'Wireless keyboard',
  },
  {
    id: nanoid(),
    assetTag: 'ORO-AC-003',
    name: 'USB-C Docking Station',
    category: 'ACCESSORY',
    status: 'ASSIGNED',
    assignedTo: 'Ananya Das',
    purchaseDate: '2024-10-11',
    purchaseCost: '14500.00',
    notes: 'Multi-port docking station',
  },
  {
    id: nanoid(),
    assetTag: 'ORO-AC-004',
    name: 'Jabra Evolve2 65',
    category: 'ACCESSORY',
    status: 'IN_REPAIR',
    assignedTo: null,
    purchaseDate: '2023-11-14',
    purchaseCost: '18500.00',
    notes: 'Microphone issue',
  },
  {
    id: nanoid(),
    assetTag: 'ORO-AC-005',
    name: 'USB-C Ethernet Adapter',
    category: 'ACCESSORY',
    status: 'RETIRED',
    assignedTo: null,
    purchaseDate: '2022-04-05',
    purchaseCost: '3200.00',
    notes: 'Replaced with newer model',
  },
  {
    id: nanoid(),
    assetTag: 'ORO-AC-006',
    name: 'Anker USB-C Hub',
    category: 'ACCESSORY',
    status: 'IN_STOCK',
    assignedTo: null,
    purchaseDate: '2025-03-05',
    purchaseCost: '6500.00',
    notes: 'Available for allocation',
  },
  {
    id: nanoid(),
    assetTag: 'ORO-AC-007',
    name: 'TP-Link USB WiFi Adapter',
    category: 'ACCESSORY',
    status: 'IN_STOCK',
    assignedTo: null,
    purchaseDate: '2025-01-08',
    purchaseCost: '1800.00',
    notes: null,
  },
]

async function seed() {
  console.log('Seeding assets...')

  await db.insert(assets).values(seedAssets)

  console.log(`Successfully inserted ${seedAssets.length} assets.`)

  process.exit(0)
}

seed().catch((error) => {
  console.error('Seed failed:', error)
  process.exit(1)
})                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     