/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AssetsNewRouteImport } from './routes/assets/new'
import { Route as ApiAssetsNewRouteImport } from './routes/api/assets/new'
import { Route as ApiAssetsStatsRouteImport } from './routes/api/assets/stats'
import { Route as AssetsIdEditRouteImport } from './routes/assets/$id/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsNewRoute = AssetsNewRouteImport.update({
  id: '/assets/new',
  path: '/assets/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssetsNewRoute = ApiAssetsNewRouteImport.update({
  id: '/api/assets/new',
  path: '/api/assets/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssetsStatsRoute = ApiAssetsStatsRouteImport.update({
  id: '/api/assets/stats',
  path: '/api/assets/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsIdEditRoute = AssetsIdEditRouteImport.update({
  id: '/assets/$id/edit',
  path: '/assets/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assets/new': typeof AssetsNewRoute
  '/api/assets/new': typeof ApiAssetsNewRoute
  '/api/assets/stats': typeof ApiAssetsStatsRoute
  '/assets/$id/edit': typeof AssetsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assets/new': typeof AssetsNewRoute
  '/api/assets/new': typeof ApiAssetsNewRoute
  '/api/assets/stats': typeof ApiAssetsStatsRoute
  '/assets/$id/edit': typeof AssetsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assets/new': typeof AssetsNewRoute
  '/api/assets/new': typeof ApiAssetsNewRoute
  '/api/assets/stats': typeof ApiAssetsStatsRoute
  '/assets/$id/edit': typeof AssetsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/assets/new'
    | '/api/assets/new'
    | '/api/assets/stats'
    | '/assets/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/assets/new'
    | '/api/assets/new'
    | '/api/assets/stats'
    | '/assets/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/assets/new'
    | '/api/assets/new'
    | '/api/assets/stats'
    | '/assets/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AssetsNewRoute: typeof AssetsNewRoute
  ApiAssetsNewRoute: typeof ApiAssetsNewRoute
  ApiAssetsStatsRoute: typeof ApiAssetsStatsRoute
  AssetsIdEditRoute: typeof AssetsIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/new': {
      id: '/assets/new'
      path: '/assets/new'
      fullPath: '/assets/new'
      preLoaderRoute: typeof AssetsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assets/new': {
      id: '/api/assets/new'
      path: '/api/assets/new'
      fullPath: '/api/assets/new'
      preLoaderRoute: typeof ApiAssetsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assets/stats': {
      id: '/api/assets/stats'
      path: '/api/assets/stats'
      fullPath: '/api/assets/stats'
      preLoaderRoute: typeof ApiAssetsStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/$id/edit': {
      id: '/assets/$id/edit'
      path: '/assets/$id/edit'
      fullPath: '/assets/$id/edit'
      preLoaderRoute: typeof AssetsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AssetsNewRoute: AssetsNewRoute,
  ApiAssetsNewRoute: ApiAssetsNewRoute,
  ApiAssetsStatsRoute: ApiAssetsStatsRoute,
  AssetsIdEditRoute: AssetsIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
